
2023/04/17
Gavin Fay

Check `bsb.dat` file by creating the `r4ss` data plots


```{r}
#load libraries
suppressPackageStartupMessages(library(tidyverse))
library(janitor)
# install.packages("pak")
# pak::pkg_install("r4ss/r4ss")
library(r4ss)
```

grab the output

```{r}
# read the model output and print diagnostic messages
replist <- SS_output(
  #dir = "../results-sandbox",
  dir = "../results/run_257",
  #dir = here::here(),
  verbose = TRUE,
  printstats = TRUE
)
```


```{r}
# plots the results
#SS_plots(replist, plot = c(7,9,11,12:19,21), dir = here::here())
#SS_plots(replist, plot = c(2), dir = here::here())
#SS_plots(replist, plot = c(1:12, 16:25), dir = here::here())
SS_plots(replist, plot = c(1:25), dir = here::here())
#SS_plots(replist, plot = c(13), dir = here::here())
```


## plot comparisons among runs
```{r}
runs_to_compare <- c(235,243:244,247:248, 250)
replists <- SSgetoutput(dirvec = file.path(
  "~/research/bsb-ss-2022/results", 
  paste("run_", runs_to_compare, sep = "")
))

# create list summarizing model results
mod.sum <- SSsummarize(replists)

# plot comparisons
SSplotComparisons(mod.sum) #, legendlabels = c("First model", "Second model"))

# # Example showing comparison of MLE to MCMC results where the mcmc would have
# # been run in the subdirectory 'c:/SS/mod1/mcmc'
# mod1 <- SS_output(dir = "c:/SS/mod1", dir.mcmc = "mcmc")
# # pass the same model twice to SSsummarize in order to plot it twice
# mod.sum <- SSsummarize(list(mod1, mod1))
# # compare MLE to MCMC
# SSplotComparisons(mod.sum,
#   legendlabels = c("MCMC", "MLE"),
#   mcmcVec = c(TRUE, FALSE)
)

```



